---
- name: Install desktop packages
  package:
    name: "{{ lookup('list', desktop_packages[ansible_distribution]) }}"
    state: latest
  become: yes

- include_tasks: fonts.yml
- include_tasks: touchpad.yml
  when: host_mode == "home"
- include_tasks: lightdm.yml
  when: host_mode == "home"
